# application-manifests.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2  # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: web-app-container
          image: nginx:latest  # Replace with your application's Docker image
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change the service type as needed
